#include "run_runtime.h"

#include <stdlib.h>

/* Forward declare the user's main function (generated by codegen). */
extern void run_main__main(void);

/*
 * The user's main runs as the first green thread so it can use the full
 * runtime (channel send/recv, yields, blocking I/O). Like Go, the process
 * exits when main returns — outstanding green threads do not keep it alive.
 */
static void run_user_main(void *arg) {
    (void)arg;
    run_main__main();
    exit(0);
}

int main(void) {
    run_scheduler_init();
    run_spawn(run_user_main, NULL);
    run_scheduler_run();
    return 0;
}
