#include "run_runtime.h"

/* Forward declare the user's main function (generated by codegen). */
extern void run_main__main(void);

int main(void) {
    run_scheduler_init();
    run_main__main();
    run_scheduler_run();
    return 0;
}
