use "fmt"

pub fun main() {
    var i = 1
    for i < 16 {
        if i % 15 == 0 {
            fmt.println("FizzBuzz")
        } else {
            if i % 3 == 0 {
                fmt.println("Fizz")
            } else {
                if i % 5 == 0 {
                    fmt.println("Buzz")
                } else {
                    fmt.print_int(i)
                    fmt.println("")
                }
            }
        }
        i = i + 1
    }
}
