#!/usr/bin/env bash
#
# update-homebrew-formula.sh — Generate/update a Homebrew formula for Run.
#
# Usage:
#   ./scripts/update-homebrew-formula.sh \
#       --version 0.1.0 \
#       --checksums-file checksums.txt \
#       --tap-dir ../homebrew-tap
#

set -euo pipefail

VERSION=""
CHECKSUMS_FILE=""
TAP_DIR=""

usage() {
    cat <<EOF
Usage: $0 --version VERSION --checksums-file FILE --tap-dir DIR

Arguments:
  --version VERSION          Release version (e.g. 0.1.0) [required]
  --checksums-file FILE      Path to the release checksums file [required]
  --tap-dir DIR              Path to the Homebrew tap repository [required]
EOF
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --version)        VERSION="$2";        shift 2 ;;
        --checksums-file) CHECKSUMS_FILE="$2"; shift 2 ;;
        --tap-dir)        TAP_DIR="$2";        shift 2 ;;
        -h|--help)        usage ;;
        *)                echo "Error: unknown argument: $1" >&2; usage ;;
    esac
done

if [[ -z "$VERSION" || -z "$CHECKSUMS_FILE" || -z "$TAP_DIR" ]]; then
    echo "Error: --version, --checksums-file, and --tap-dir are required." >&2
    usage
fi

if [[ ! -f "$CHECKSUMS_FILE" ]]; then
    echo "Error: checksums file not found: $CHECKSUMS_FILE" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Extract SHA256 hashes for each platform/arch combo
# ---------------------------------------------------------------------------

get_sha256() {
    local os="$1"
    local arch="$2"
    local tarball="run-${VERSION}-${os}-${arch}.tar.gz"
    local hash
    hash="$(grep "$tarball" "$CHECKSUMS_FILE" | awk '{print $1}')"
    if [[ -z "$hash" ]]; then
        echo "Error: no checksum found for $tarball in $CHECKSUMS_FILE" >&2
        exit 1
    fi
    echo "$hash"
}

SHA_DARWIN_ARM64="$(get_sha256 darwin arm64)"
SHA_DARWIN_AMD64="$(get_sha256 darwin amd64)"
SHA_LINUX_ARM64="$(get_sha256 linux arm64)"
SHA_LINUX_AMD64="$(get_sha256 linux amd64)"

echo "==> SHA256 hashes:"
echo "    darwin-arm64: $SHA_DARWIN_ARM64"
echo "    darwin-amd64: $SHA_DARWIN_AMD64"
echo "    linux-arm64:  $SHA_LINUX_ARM64"
echo "    linux-amd64:  $SHA_LINUX_AMD64"

# ---------------------------------------------------------------------------
# Generate Formula/run.rb
# ---------------------------------------------------------------------------

FORMULA_DIR="${TAP_DIR}/Formula"
mkdir -p "$FORMULA_DIR"

FORMULA_FILE="${FORMULA_DIR}/run.rb"

cat > "$FORMULA_FILE" <<RUBY
# frozen_string_literal: true
# This file is auto-generated by scripts/update-homebrew-formula.sh.
# Do not edit manually.

class Run < Formula
  desc "Systems programming language compiler with Go simplicity and low-level control"
  homepage "https://runlang.dev"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/marsolab/runlang/releases/download/v${VERSION}/run-${VERSION}-darwin-arm64.tar.gz"
      sha256 "${SHA_DARWIN_ARM64}"
    end

    on_intel do
      url "https://github.com/marsolab/runlang/releases/download/v${VERSION}/run-${VERSION}-darwin-amd64.tar.gz"
      sha256 "${SHA_DARWIN_AMD64}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/marsolab/runlang/releases/download/v${VERSION}/run-${VERSION}-linux-arm64.tar.gz"
      sha256 "${SHA_LINUX_ARM64}"
    end

    on_intel do
      url "https://github.com/marsolab/runlang/releases/download/v${VERSION}/run-${VERSION}-linux-amd64.tar.gz"
      sha256 "${SHA_LINUX_AMD64}"
    end
  end

  depends_on "zig"

  def install
    bin.install "bin/run"
    lib.install "lib/librunrt.a"
    (include/"run").install Dir["include/run/*.h"]
  end

  test do
    assert_match "run version #{version}", shell_output("#{bin}/run --version")
  end
end
RUBY

echo "==> Formula written to: $FORMULA_FILE"
echo "==> Done. Review the formula, then commit and push to the tap repository."
