apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strapi.fullname" . }}
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_JWT_SECRET: {{ .Values.strapi.adminJwtSecret | default (randAlphaNum 32) | quote }}
  API_TOKEN_SALT: {{ .Values.strapi.apiTokenSalt | default (randAlphaNum 32) | quote }}
  APP_KEYS: {{ .Values.strapi.appKeys | default (printf "%s,%s,%s,%s" (randAlphaNum 16) (randAlphaNum 16) (randAlphaNum 16) (randAlphaNum 16)) | quote }}
  TRANSFER_TOKEN_SALT: {{ .Values.strapi.transferTokenSalt | default (randAlphaNum 32) | quote }}
  JWT_SECRET: {{ .Values.strapi.jwtSecret | default (randAlphaNum 32) | quote }}
  {{- if .Values.postgresql.enabled }}
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | default (randAlphaNum 24) | quote }}
  {{- else if .Values.externalDatabase.enabled }}
  DATABASE_PASSWORD: {{ .Values.externalDatabase.password | quote }}
  {{- end }}
